import { act, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { axe } from 'jest-axe'
import { describe, expect, it } from 'vitest'
import { fakeClient } from './fakeClient'
import { renderApp } from './ui'

const where = () => screen.getByTestId('where').textContent

describe('login', () => {
  it('has no axe violations', async () => {
    const f = fakeClient({ session: null })
    const { container } = renderApp(f.client, '/login')
    await screen.findByRole('heading', { name: 'Log in' })
    expect((await axe(container)).violations).toEqual([])
  })
  it('signs in and goes to My boards', async () => {
    const f = fakeClient({ session: null })
    const user = userEvent.setup()
    renderApp(f.client, '/login')
    await user.type(await screen.findByLabelText('Email'), 'a@b.co')
    await user.type(screen.getByLabelText('Password'), 'hunter2hunter2')
    await user.click(screen.getByRole('button', { name: 'Log in' }))
    expect(f.auth.signInWithPassword).toHaveBeenCalledWith({ email: 'a@b.co', password: 'hunter2hunter2' })
    await waitFor(() => expect(where()).toBe('/boards'))
  })
  it('shows the server error in a role=alert', async () => {
    const f = fakeClient({ session: null })
    f.auth.signInWithPassword.mockResolvedValueOnce({ error: { message: 'Invalid login credentials' } } as never)
    const user = userEvent.setup()
    renderApp(f.client, '/login')
    await user.type(await screen.findByLabelText('Email'), 'a@b.co')
    await user.type(screen.getByLabelText('Password'), 'wrongwrong')
    await user.click(screen.getByRole('button', { name: 'Log in' }))
    const alert = await screen.findByRole('alert')
    expect(alert).toHaveTextContent('Invalid login credentials')
    expect(screen.getByLabelText('Email')).toHaveAttribute('aria-describedby', alert.id)
    expect(screen.getByLabelText('Email')).toHaveAttribute('aria-invalid', 'true')
    expect(where()).toBe('/login')
  })
  it('wires Google OAuth and hides GitHub by default', async () => {
    const f = fakeClient({ session: null })
    const user = userEvent.setup()
    renderApp(f.client, '/login')
    await user.click(await screen.findByRole('button', { name: 'Continue with Google' }))
    expect(screen.queryByRole('button', { name: 'Continue with GitHub' })).toBeNull()
    expect(f.auth.signInWithOAuth.mock.calls.map((c) => (c as unknown as [{ provider: string }])[0].provider)).toEqual(['google'])
  })
  it('redirects protected routes to login when logged out', async () => {
    renderApp(fakeClient({ session: null }).client, '/boards')
    await waitFor(() => expect(where()).toBe('/login'))
  })
})

describe('register', () => {
  it('has no axe violations', async () => {
    const { container } = renderApp(fakeClient({ session: null }).client, '/register')
    await screen.findByRole('heading', { name: 'Register' })
    expect((await axe(container)).violations).toEqual([])
  })
  it('validates passwords client-side, then shows a neutral check-your-email notice', async () => {
    const f = fakeClient({ session: null })
    const user = userEvent.setup()
    renderApp(f.client, '/register')
    await user.type(await screen.findByLabelText('Email'), 'a@b.co')
    await user.type(screen.getByLabelText('Password'), 'longenough1')
    await user.type(screen.getByLabelText('Confirm password'), 'different123')
    await user.click(screen.getByRole('button', { name: 'Create account' }))
    expect(screen.getByRole('alert')).toHaveTextContent('do not match')
    expect(f.auth.signUp).not.toHaveBeenCalled()
    await user.clear(screen.getByLabelText('Confirm password'))
    await user.type(screen.getByLabelText('Confirm password'), 'longenough1')
    await user.click(screen.getByRole('button', { name: 'Create account' }))
    expect(await screen.findByRole('status')).toHaveTextContent(/If this address can be registered/)
  })
})

describe('password reset', () => {
  it('requests a link with a generic confirmation', async () => {
    const f = fakeClient({ session: null })
    const user = userEvent.setup()
    const { container } = renderApp(f.client, '/reset')
    await user.type(await screen.findByLabelText('Email'), 'a@b.co')
    await user.click(screen.getByRole('button', { name: 'Send reset link' }))
    expect(await screen.findByRole('status')).toHaveTextContent('If an account exists')
    expect(f.auth.resetPasswordForEmail).toHaveBeenCalled()
    expect((await axe(container)).violations).toEqual([])
  })
  it('shows the new-password form after a recovery event and saves it', async () => {
    const f = fakeClient({ session: null })
    const user = userEvent.setup()
    const { container } = renderApp(f.client, '/reset')
    await screen.findByLabelText('Email')
    act(() => f.emit('PASSWORD_RECOVERY'))
    await user.type(await screen.findByLabelText('New password'), 'brandnewpass1')
    await user.type(screen.getByLabelText('Confirm new password'), 'brandnewpass1')
    expect((await axe(container)).violations).toEqual([])
    await user.click(screen.getByRole('button', { name: 'Set password' }))
    expect(f.auth.updateUser).toHaveBeenCalledWith({ password: 'brandnewpass1' })
    await waitFor(() => expect(where()).toBe('/boards'))
  })
})

describe('account deletion', () => {
  it('requires typing the email, removes thumbnails, calls the RPC and ends at login with a notice', async () => {
    const f = fakeClient()
    const user = userEvent.setup()
    const { container } = renderApp(f.client, '/account')
    const btn = await screen.findByRole('button', { name: 'Delete my account' })
    expect(btn).toBeDisabled()
    expect((await axe(container)).violations).toEqual([])
    await user.type(screen.getByLabelText(/Type me@example.com/), 'me@example.com')
    expect(btn).toBeEnabled()
    await user.click(btn)
    await waitFor(() => expect(f.rpc).toHaveBeenCalledWith('delete_my_account'))
    expect(f.storage.from).toHaveBeenCalledWith('thumbnails')
    await waitFor(() => expect(where()).toBe('/login'))
    expect(await screen.findByRole('status')).toHaveTextContent(/deleted/)
    expect(f.auth.signOut).toHaveBeenCalledWith({ scope: 'local' })
  })
  it('keeps the user on the page with an alert when deletion fails', async () => {
    const f = fakeClient()
    f.rpc.mockResolvedValueOnce({ data: null, error: { message: 'boom' } } as never)
    const user = userEvent.setup()
    renderApp(f.client, '/account')
    await user.type(await screen.findByLabelText(/Type me@example.com/), 'me@example.com')
    await user.click(screen.getByRole('button', { name: 'Delete my account' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('boom')
    expect(where()).toBe('/account')
  })

  it('does not delete the account when thumbnails could not be removed', async () => {
    const f = fakeClient()
    f.bucket.remove.mockResolvedValueOnce({ error: { message: 'storage denied' } } as never)
    const user = userEvent.setup()
    renderApp(f.client, '/account')
    await user.type(await screen.findByLabelText(/Type me@example.com/), 'me@example.com')
    await user.click(screen.getByRole('button', { name: 'Delete my account' }))
    expect(await screen.findByRole('alert')).toHaveTextContent(/not deleted.*storage denied/)
    expect(f.rpc).not.toHaveBeenCalled()
    expect(f.auth.signOut).not.toHaveBeenCalled()
    expect(where()).toBe('/account')
  })
  it('does not delete the account when Storage RLS silently removes nothing', async () => {
    const f = fakeClient()
    f.bucket.remove.mockResolvedValueOnce({ data: [], error: null } as never)
    const user = userEvent.setup()
    renderApp(f.client, '/account')
    await user.type(await screen.findByLabelText(/Type me@example.com/), 'me@example.com')
    await user.click(screen.getByRole('button', { name: 'Delete my account' }))
    expect(await screen.findByRole('alert')).toHaveTextContent(/not deleted.*could not be removed/)
    expect(f.rpc).not.toHaveBeenCalled()
  })
  it('shows the deleted notice once and clears it', async () => {
    const f = fakeClient()
    const user = userEvent.setup()
    renderApp(f.client, '/account')
    await user.type(await screen.findByLabelText(/Type me@example.com/), 'me@example.com')
    await user.click(screen.getByRole('button', { name: 'Delete my account' }))
    expect(await screen.findByRole('status')).toHaveTextContent(/deleted/)
    await user.click(screen.getByRole('link', { name: 'Register' }))
    await user.click(await screen.findByRole('link', { name: 'Log in' }))
    expect(screen.queryByRole('status')).not.toBeInTheDocument()
  })
})

it('offers GitHub only when enabled', async () => {
  const { oauthProviders } = await import('../../src/auth/OAuthButtons')
  expect(oauthProviders(false).map((p) => p.id)).toEqual(['google'])
  expect(oauthProviders(true).map((p) => p.id)).toEqual(['google', 'github'])
})
